//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Areas.Stockist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITy()
        {
            this.SubAreas = new HashSet<SubArea>();
        }
    
        public int CITYID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<int> STATEID { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual STATE STATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubArea> SubAreas { get; set; }
    }
}
