//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public int COUNTRYID { get; set; }
        public string COUNTRYNAME { get; set; }
        public string ACTIVE { get; set; }
    }
}
