//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foursolarwalloflove
    {
        public int foursolarwallofloveID { get; set; }
        public string tittle { get; set; }
        public string shortdesc { get; set; }
        public string fulldesc { get; set; }
        public string imageurl { get; set; }
        public string pages { get; set; }
        public string url { get; set; }
        public string seotittle { get; set; }
        public string seokeywords { get; set; }
        public string seometatags { get; set; }
        public string urltittle { get; set; }
    }
}
