//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hhcControlPanelIPStat
    {
        public int CPIPID { get; set; }
        public string CPIP { get; set; }
        public Nullable<System.DateTime> CPLoginTime { get; set; }
        public Nullable<System.DateTime> CPLogoutTime { get; set; }
        public string CPLoginID { get; set; }
    }
}
