//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Htherapatic
    {
        public int HtherapaticID { get; set; }
        public string HtherapaticDESC { get; set; }
        public string HtherapaticSTATUS { get; set; }
        public string htheterocode { get; set; }
        public string hthetroname { get; set; }
        public string htdivisionid { get; set; }
    }
}
