//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hvproductslist
    {
        public int HvproductslistID { get; set; }
        public string HvproductslistNAME { get; set; }
        public string HvproductslistDESC { get; set; }
        public string Hvproductslistcompanyid { get; set; }
        public string Hproductslistcompanyid { get; set; }
        public string hvstockistid { get; set; }
        public string Hproductslistcompanyname { get; set; }
        public string hvstockistname { get; set; }
    }
}
