//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> Mobile { get; set; }
    }
}
