//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDORSUser
    {
        public int VENDORID { get; set; }
        public string VendorSPECIALISATION { get; set; }
        public string QUALIFICATION { get; set; }
        public Nullable<int> AGE { get; set; }
        public string GENDER { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> ZIP { get; set; }
        public string MOBILE { get; set; }
        public string ACTIVE { get; set; }
        public string PHOTO { get; set; }
        public string Designation { get; set; }
        public string BriefProfile { get; set; }
        public string PresentPosition { get; set; }
        public string Qualifications { get; set; }
        public string SpecialTraining { get; set; }
        public string Experience { get; set; }
        public string Expertise { get; set; }
        public string AchievementsBreakthroughCases { get; set; }
        public string Publications { get; set; }
        public string AwardsAndHonors { get; set; }
        public string AcademicExposure { get; set; }
        public string TalkDelivered { get; set; }
        public string Other { get; set; }
        public string Media { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string vendortype { get; set; }
    }
}
