//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDORSPECIALIZATION
    {
        public int SPECIALIZATIONID { get; set; }
        public string SPECIALIZATIONNAME { get; set; }
        public string SPECIALIZATIONDESC { get; set; }
        public string Procedures { get; set; }
        public string ACTIVE { get; set; }
        public string Vendortype { get; set; }
    }
}
