//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hdivision
    {
        public int HdivisionID { get; set; }
        public string HdivisionDESC { get; set; }
        public string heterodivisoncode { get; set; }
        public string hdname { get; set; }
        public string Active { get; set; }
    }
}
