//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hhcmonthyear
    {
        public int hhcmonthyearID { get; set; }
        public string monthid { get; set; }
        public string monthname { get; set; }
        public string yearid { get; set; }
        public string yearname { get; set; }
        public string Monthyear { get; set; }
        public string active { get; set; }
    }
}
