//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hhcprimarysale
    {
        public int hhcprimarysalesID { get; set; }
        public string billingdocument { get; set; }
        public string billingdate { get; set; }
        public string stockistcode { get; set; }
        public string stockistsapid { get; set; }
        public string stockistname { get; set; }
        public string heterosapproductcode { get; set; }
        public string heterosapproductname { get; set; }
        public string sapproductquantity { get; set; }
        public string productid { get; set; }
        public string quantity { get; set; }
        public string rate { get; set; }
        public string value { get; set; }
        public string headquarterid { get; set; }
        public string headquartername { get; set; }
        public string stateid { get; set; }
        public string statename { get; set; }
        public string zoneid { get; set; }
        public string zonename { get; set; }
        public string divisionname { get; set; }
        public string divisionid { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string deliverystatus { get; set; }
        public Nullable<int> monthyearid { get; set; }
    }
}
