//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hhcsecondarysale
    {
        public int hhcsecondarysalesID { get; set; }
        public string stockistname { get; set; }
        public string stockistid { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string stockistproductname { get; set; }
        public string package { get; set; }
        public Nullable<int> openingstock { get; set; }
        public Nullable<int> purshcasequantity { get; set; }
        public Nullable<int> purchasereturn { get; set; }
        public Nullable<int> salereturn { get; set; }
        public Nullable<int> closing { get; set; }
        public string filepath { get; set; }
        public string heteroproductid { get; set; }
        public string heteroproductname { get; set; }
        public string headquaterid { get; set; }
        public string headquartername { get; set; }
        public string heteroproductsapid { get; set; }
        public string stateid { get; set; }
        public string statename { get; set; }
        public string zoneid { get; set; }
        public string zonename { get; set; }
        public string divisionname { get; set; }
        public string divisionid { get; set; }
        public Nullable<int> monthyearid { get; set; }
        public Nullable<int> salequantity { get; set; }
        public string sapmaterialcode { get; set; }
    }
}
