//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hstockistdetail
    {
        public int HstockistdetailsID { get; set; }
        public string hsfullname { get; set; }
        public string hslastname { get; set; }
        public string hsemailid { get; set; }
        public string hsmobile { get; set; }
        public string hspwd { get; set; }
        public string hssapcustomerid { get; set; }
        public string hsplotno { get; set; }
        public string hsadressone { get; set; }
        public string hsadresstwo { get; set; }
        public string hscountry { get; set; }
        public string hsstate { get; set; }
        public string hsheadquater { get; set; }
        public string hssubarea { get; set; }
        public string hsdivision { get; set; }
        public string hscnf { get; set; }
        public string hstherapatic { get; set; }
        public string hspincode { get; set; }
        public string hstelephone { get; set; }
        public string hsfax { get; set; }
        public string hsgstprovisionalid { get; set; }
        public string hspan { get; set; }
        public string hsspocname { get; set; }
        public string hsspocmobile { get; set; }
        public string hsssistatus { get; set; }
        public string hsdruglicenceno { get; set; }
        public string hszone { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
