//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFileName
    {
        public int UploadFileId { get; set; }
        public string UploadFileName1 { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string UploadedBy { get; set; }
    }
}
