//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcMkTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdminLogin
    {
        public int OtherAdminId { get; set; }
        public string Email { get; set; }
        public string UserPwd { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Permissions { get; set; }
        public string Adress { get; set; }
        public string ActiveStatus { get; set; }
        public string State { get; set; }
        public string country { get; set; }
        public string Mobile { get; set; }
    }
}
