<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/admin-hhc/adminbasepage.master" CodeBehind="manage-admins.aspx.vb" Inherits="betatesting.manage_admins1" %>




<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
   <div class="col-xs-12 col-sm-12 col-md-12">
   <h1>Manage Users</h1>
   </div>
   
   <div class="col-xs-12 col-sm-12 col-md-12">
   
    <asp:Button ID="BtnAddNew" runat="server" Text="Add New" 
                    CausesValidation="False" />

    <asp:Button ID="BtnView" runat="server" Text="View / Search" 
                    CausesValidation="False" />
    <asp:Label ID="LblMsg" runat="server" Font-Bold="True" Font-Size="Medium"></asp:Label>
     <br />
</div>

       
    <asp:Panel ID="PnlAddNew" runat="server" Visible="false">



 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
 <h4>Add New Admin User</h4>
 </div>

   <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
               <asp:TextBox ID="TxtName" runat="server" placeholder="Enter Name" CssClass="form-control"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RFVName" runat="server" 
            ControlToValidate="TxtName" Display="None" ErrorMessage="Enter Name"></asp:RequiredFieldValidator>


        </div>

 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">

              <asp:TextBox ID="TxtLoginId" runat="server" placeholder="Enter Login Id" CssClass="form-control"></asp:TextBox>
        <asp:RequiredFieldValidator ID="RFVLoginId" runat="server" 
            ControlToValidate="TxtLoginId" Display="None" ErrorMessage="Enter Login Id"></asp:RequiredFieldValidator>
        
        </div>


 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
            <asp:TextBox ID="TxtEmailId" runat="server" placeholder="Enter Email Id" CssClass="form-control"></asp:TextBox>
            <asp:RegularExpressionValidator ID="REVEmailID" runat="server" 
                ControlToValidate="TxtEmailId" Display="None" ErrorMessage="Invalid Email ID" 
                ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
            <br />Enter Email Id to send login details to the user
        </div>


 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
<h4>            Select Permitted Sections</h4>
        </div>


<div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">

<div class="col-xs-12 col-sm-12 col-md-6" style="margin:1% 0;">
            <asp:CheckBoxList ID="CBLSections" runat="server" RepeatColumns="4" 
                RepeatDirection="Horizontal">
                 <asp:ListItem>CMS</asp:ListItem>
                <asp:ListItem>Users</asp:ListItem>
              </asp:CheckBoxList>
</div>
</div>
 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0; text-align:center;">
            <asp:Button ID="BtnSave" runat="server" Text="Save" />
        &nbsp;
        <asp:Button ID="BtnCancel" runat="server" Text="Cancel" />
        <br />
        <asp:ValidationSummary ID="ValidationSummary1" runat="server" 
            ShowMessageBox="True" ShowSummary="False" />
        </div>
        <div>
            Note : Password will be auto generated by the system
        </div>
      
    
    </asp:Panel>

    <asp:Panel ID="PnlView" runat="server">

 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
<h4>Search</h4>
        </div>
        
 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
            <asp:TextBox ID="TxtName_s" runat="server" placeholder="Enter Name" CssClass="form-control"></asp:TextBox>
        </div>

 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
            <asp:TextBox ID="TxtLoginId_s" runat="server" placeholder="Enter Login Id" CssClass="form-control"></asp:TextBox>
        </div>

 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0;">
            <asp:TextBox ID="TxtEmailId_s" runat="server" placeholder="Email Id" CssClass="form-control"></asp:TextBox>
        </div>

 <div class="col-xs-12 col-sm-12 col-md-12" style="margin:1% 0; text-align:center;">
            <asp:Button ID="BtnSearch" runat="server" Text="Search" 
                        CausesValidation="False" />
                    &nbsp;<asp:Button ID="BtnViewAll" runat="server" Text="View All" 
                        CausesValidation="False" />
        </div>
        <div>

            <asp:GridView ID="GVAdmins" runat="server" 
                        AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="hhcAdminLoginsId">
                    <HeaderStyle CssClass="GridHeaderStyle" />
                    <RowStyle CssClass="GridRowStyle" />
                    <AlternatingRowStyle CssClass="GridAlternateRowStyle" />
                    <EmptyDataTemplate><table width="600"><tr><td class="GridHeaderStyle">No Users Found !</td></tr></table></EmptyDataTemplate>
                    <Columns>
                        <asp:BoundField DataField="UserName" HeaderText="User Name" 
                            SortExpression="UserName" />
                        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        <asp:BoundField DataField="Permissions" HeaderText="Permissions" 
                            SortExpression="Permissions" />
                        <asp:BoundField DataField="EmailID" HeaderText="Email ID" 
                            SortExpression="EmailID" />
                        <asp:ButtonField CommandName="CmdEdit" HeaderText="Edit" Text="Edit" />
                        <asp:TemplateField ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton ID="LnkBtnResetPwd" runat="server" CausesValidation="false" 
                                    CommandName="CmdResetPwd" Text="Reset Password" 
                                    OnClientClick="return confirm('Are You Sure You Want To Reset Password');"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField ShowHeader="False">
                            <ItemTemplate>
                                <asp:LinkButton ID="LnkBtnActive" runat="server" CausesValidation="false" 
                                    CommandName="CmdActive" Text='<%# Eval("ActiveStatus") %>'></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
        </div>
            
          
        </asp:Panel>
    <asp:Label ID="LblGridSource" runat="server" Visible="false"></asp:Label>
    <asp:Label ID="LblOtherAdminID" runat="server" Visible="false"></asp:Label>
    <asp:Label ID="LblActiveStatus" runat="server" Visible="false"></asp:Label>
    <asp:Label ID="LblPassword" runat="server" Visible="false"></asp:Label>
</asp:Content>