//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionWiseProductPrice
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string MaterialCode { get; set; }
        public string NameOfTheProduct { get; set; }
        public string PackSize { get; set; }
        public string Mrp { get; set; }
        public string Nsp { get; set; }
        public string Ptr { get; set; }
        public string Pts { get; set; }
        public string HsnCode { get; set; }
        public string Gst { get; set; }
        public string DivisionName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
