//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestSsDataEntities : DbContext
    {
        public TestSsDataEntities()
            : base("name=TestSsDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<DivisionWiseProductPrice> DivisionWiseProductPrices { get; set; }
        public virtual DbSet<DivisionWiseProduct> DivisionWiseProducts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Hstockistdetail> Hstockistdetails { get; set; }
        public virtual DbSet<TotalStockist> TotalStockists { get; set; }
    }
}
