//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalStockist
    {
        public int Id { get; set; }
        public string StkId { get; set; }
        public string StkName { get; set; }
        public string Region { get; set; }
        public string DeliverPlant { get; set; }
        public string DisChannel { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string DivisionName { get; set; }
        public Nullable<int> SalesOfficeId { get; set; }
        public string SalesOfficeName { get; set; }
    }
}
