//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcBetaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        public int CITYID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<int> STATEID { get; set; }
        public string ACTIVE { get; set; }
    }
}
