//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcBetaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hproductslistdescription
    {
        public int HproductslistdescriptionID { get; set; }
        public string HproductslistdescriptionDESC { get; set; }
        public string STATUS { get; set; }
        public string Hproductslistcompanyid { get; set; }
        public string hpdquantityperpack { get; set; }
        public string hpdquantityperstrip { get; set; }
        public Nullable<System.DateTime> hpdratevalidform { get; set; }
        public string hpdpricetoretailer { get; set; }
        public string hpdmrp { get; set; }
        public string hpdstandardrate { get; set; }
        public string hpdpricetostockist { get; set; }
        public string hpdbrandname { get; set; }
        public string hdpcategoryname { get; set; }
        public string hpddivisionname { get; set; }
        public string hdpmanfacturename { get; set; }
    }
}
