//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcBetaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hproductslist
    {
        public int HproductslistID { get; set; }
        public string HproductslistNAME { get; set; }
        public string HproductslistDESC { get; set; }
        public string Hproductslistcompanyid { get; set; }
    }
}
