//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcBetaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherAdminPermission
    {
        public int OtherAdminPermissionID { get; set; }
        public Nullable<int> OtherAdminId { get; set; }
        public string SectionPermitted { get; set; }
    }
}
