//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcPmsTst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmsRegistrationdetail
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Emailid { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<int> Mobile { get; set; }
    }
}
